import Head from "next/head";
import { useTina } from "tinacms/dist/react";
import client from "../.tina/__generated__/client";
import { TinaMarkdown } from "tinacms/dist/rich-text";
import type { TinaMarkdownContent } from "tinacms/dist/rich-text";

export default function Home(props) {
  const { data } = useTina<{ page: { body: TinaMarkdownContent } }>({
    query: props.query,
    variables: props.variables,
    data: props.data,
  });
  return (
    <>
      <Head>
        <title>Alexis Sara</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TinaMarkdown content={data.page.body} />
    </>
  );
}

export const getStaticProps = async () => {
  const tinaProps = await client.queries.page({ relativePath: "home.md" });
  return {
    props: {
      data: tinaProps.data,
      query: tinaProps.query,
      variables: tinaProps.variables,
    },
  };
};
